package com.exam.proyectsvc.pojo.database;
// Generated Nov 26, 2019 9:43:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrdProducto generated by hbm2java
 */
@Entity
@Table(name="prd_producto")
public class PrdProducto  implements java.io.Serializable {


     private String prdIdproducto;
     private PrdTipoproducto prdTipoproducto;
     private int prdIdpropietario;
     private String prdNombre;
     private Double prdSaldo;
     private Double prdMonto;
     private Double prdTasa;
     private Integer prdCorte;
     private Double prdInteresAcumulado;

    public PrdProducto() {
    }

	
    public PrdProducto(String prdIdproducto, PrdTipoproducto prdTipoproducto, int prdIdpropietario, Double prdSaldo) {
        this.prdIdproducto = prdIdproducto;
        this.prdTipoproducto = prdTipoproducto;
        this.prdIdpropietario = prdIdpropietario;
        this.prdSaldo = prdSaldo;
    }
    public PrdProducto(String prdIdproducto, PrdTipoproducto prdTipoproducto, int prdIdpropietario, String prdNombre, Double prdSaldo, Double prdMonto, Double prdTasa, Integer prdCorte, Double prdInteresAcumulado) {
       this.prdIdproducto = prdIdproducto;
       this.prdTipoproducto = prdTipoproducto;
       this.prdIdpropietario = prdIdpropietario;
       this.prdNombre = prdNombre;
       this.prdSaldo = prdSaldo;
       this.prdMonto = prdMonto;
       this.prdTasa = prdTasa;
       this.prdCorte = prdCorte;
       this.prdInteresAcumulado = prdInteresAcumulado;
    }
   
    @Id
    @Column(name="prd_idproducto", unique=true, nullable=false, length=20)
    public String getPrdIdproducto() {
        return this.prdIdproducto;
    }
    
    public void setPrdIdproducto(String prdIdproducto) {
        this.prdIdproducto = prdIdproducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prd_idtipoproducto", nullable=false)
    public PrdTipoproducto getPrdTipoproducto() {
        return this.prdTipoproducto;
    }
    
    public void setPrdTipoproducto(PrdTipoproducto prdTipoproducto) {
        this.prdTipoproducto = prdTipoproducto;
    }

    
    @Column(name="prd_idpropietario", nullable=false)
    public int getPrdIdpropietario() {
        return this.prdIdpropietario;
    }
    
    public void setPrdIdpropietario(int prdIdpropietario) {
        this.prdIdpropietario = prdIdpropietario;
    }

    
    @Column(name="prd_nombre", length=100)
    public String getPrdNombre() {
        return this.prdNombre;
    }
    
    public void setPrdNombre(String prdNombre) {
        this.prdNombre = prdNombre;
    }

    
    @Column(name="prd_saldo", nullable=false, precision=8)
    public Double getPrdSaldo() {
        return this.prdSaldo;
    }
    
    public void setPrdSaldo(Double prdSaldo) {
        this.prdSaldo = prdSaldo;
    }

    
    @Column(name="prd_monto", precision=8)
    public Double getPrdMonto() {
        return this.prdMonto;
    }
    
    public void setPrdMonto(Double prdMonto) {
        this.prdMonto = prdMonto;
    }

    
    @Column(name="prd_tasa", precision=8)
    public Double getPrdTasa() {
        return this.prdTasa;
    }
    
    public void setPrdTasa(Double prdTasa) {
        this.prdTasa = prdTasa;
    }

    
    @Column(name="prd_corte")
    public Integer getPrdCorte() {
        return this.prdCorte;
    }
    
    public void setPrdCorte(Integer prdCorte) {
        this.prdCorte = prdCorte;
    }

    
    @Column(name="prd_interes_acumulado", precision=8)
    public Double getPrdInteresAcumulado() {
        return this.prdInteresAcumulado;
    }
    
    public void setPrdInteresAcumulado(Double prdInteresAcumulado) {
        this.prdInteresAcumulado = prdInteresAcumulado;
    }




}


