package com.exam.proyectsvc.pojo.database;
// Generated Nov 26, 2019 9:43:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrdTipoproducto generated by hbm2java
 */
@Entity
@Table(name="prd_tipoproducto"
    ,schema="lb_product"
)
public class PrdTipoproducto  implements java.io.Serializable {


     private int tipoId;
     private String tipoNombre;
     private Set<PrdProducto> prdProductos = new HashSet<PrdProducto>(0);

    public PrdTipoproducto() {
    }

	
    public PrdTipoproducto(int tipoId, String tipoNombre) {
        this.tipoId = tipoId;
        this.tipoNombre = tipoNombre;
    }
    public PrdTipoproducto(int tipoId, String tipoNombre, Set<PrdProducto> prdProductos) {
       this.tipoId = tipoId;
       this.tipoNombre = tipoNombre;
       this.prdProductos = prdProductos;
    }
   
     @Id 

    
    @Column(name="tipo_id", unique=true, nullable=false)
    public int getTipoId() {
        return this.tipoId;
    }
    
    public void setTipoId(int tipoId) {
        this.tipoId = tipoId;
    }

    
    @Column(name="tipo_nombre", nullable=false, length=100)
    public String getTipoNombre() {
        return this.tipoNombre;
    }
    
    public void setTipoNombre(String tipoNombre) {
        this.tipoNombre = tipoNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prdTipoproducto")
    public Set<PrdProducto> getPrdProductos() {
        return this.prdProductos;
    }
    
    public void setPrdProductos(Set<PrdProducto> prdProductos) {
        this.prdProductos = prdProductos;
    }




}


